scene = None
view = None
window_container = None
main_window = None
default_mesh = None
scene_manager = None
image_searcher = None
camera_controller = None
app = None
input_handler = None
resources_manager = None
post_load_widget = None
loading_widget = None
image_data_widget = None
map_widget = None

# defaultImageDirectory = 'C:\\Users\\serba\\Desktop\\train2017'
working_directory = 'C:\\Users\\serba\\Desktop\\Thermal'
texture_size = 255
max_dataset_length = 0
